/*
Author: Evan Brooks
Date: 2017
*/

/*Select restaurants which serve breakfast*/
SELECT tbl_RESTAURANT.R_NAME, tbl_RESTAURANT.R_GENRE, tbl_RESTAURANT.R_PRICE_RANGE, tbl_HOURS.H_BREAKFAST, tbl_ADDRESS.A_CITY
FROM (tbl_RESTAURANT INNER JOIN tbl_ADDRESS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_ADDRESS.R_RESTAURANT_ID) INNER JOIN tbl_HOURS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_HOURS.R_RESTAURANT_ID
WHERE (((tbl_HOURS.H_BREAKFAST)=Yes))
ORDER BY tbl_RESTAURANT.R_PRICE_RANGE;

/*Select restaurants which serve lunch*/
SELECT tbl_RESTAURANT.R_NAME, tbl_RESTAURANT.R_GENRE, tbl_RESTAURANT.R_PRICE_RANGE, tbl_HOURS.H_LUNCH, tbl_ADDRESS.A_CITY
FROM (tbl_RESTAURANT INNER JOIN tbl_ADDRESS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_ADDRESS.R_RESTAURANT_ID) INNER JOIN tbl_HOURS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_HOURS.R_RESTAURANT_ID
WHERE (((tbl_HOURS.H_LUNCH)=Yes))
ORDER BY tbl_RESTAURANT.R_PRICE_RANGE;

/*Select restaurants which serve dinner*/
SELECT tbl_RESTAURANT.R_NAME, tbl_RESTAURANT.R_GENRE, tbl_RESTAURANT.R_PRICE_RANGE, tbl_HOURS.H_DINNER, tbl_ADDRESS.A_CITY
FROM (tbl_RESTAURANT INNER JOIN tbl_ADDRESS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_ADDRESS.R_RESTAURANT_ID) INNER JOIN tbl_HOURS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_HOURS.R_RESTAURANT_ID
WHERE (((tbl_HOURS.H_DINNER)=Yes))
ORDER BY tbl_RESTAURANT.R_PRICE_RANGE;

/*Select restaurants which serve late night food*/
SELECT tbl_RESTAURANT.R_NAME, tbl_RESTAURANT.R_GENRE, tbl_RESTAURANT.R_PRICE_RANGE, tbl_RESTAURANT.R_BAR, tbl_HOURS.H_LATENIGHT, tbl_ADDRESS.A_CITY
FROM (tbl_RESTAURANT INNER JOIN tbl_ADDRESS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_ADDRESS.R_RESTAURANT_ID) INNER JOIN tbl_HOURS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_HOURS.R_RESTAURANT_ID
WHERE (((tbl_HOURS.H_LATENIGHT)=Yes))
ORDER BY tbl_RESTAURANT.R_PRICE_RANGE;


/*Select restaurants which serve all meals*/
SELECT tbl_RESTAURANT.R_NAME, tbl_RESTAURANT.R_RATING, tbl_RESTAURANT.R_GENRE, tbl_RESTAURANT.R_PRICE_RANGE, tbl_ADDRESS.A_CITY, tbl_HOURS.H_BREAKFAST, tbl_HOURS.H_LUNCH, tbl_HOURS.H_DINNER, tbl_HOURS.H_LATENIGHT
FROM (tbl_RESTAURANT INNER JOIN tbl_HOURS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_HOURS.R_RESTAURANT_ID) INNER JOIN tbl_ADDRESS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_ADDRESS.R_RESTAURANT_ID;

/*Select restaurants with higher ratings*/
SELECT tbl_RESTAURANT.R_NAME, tbl_RESTAURANT.R_GENRE, tbl_RESTAURANT.R_PRICE_RANGE, tbl_HOURS.H_DINNER, tbl_ADDRESS.A_CITY
FROM (tbl_RESTAURANT INNER JOIN tbl_ADDRESS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_ADDRESS.R_RESTAURANT_ID) INNER JOIN tbl_HOURS ON tbl_RESTAURANT.R_RESTAURANT_ID = tbl_HOURS.R_RESTAURANT_ID
WHERE (((tbl_RESTAURANT.R_RATING)="4 Points"))
OR (((tbl_RESTAURANT.R_RATING)="5 Points"))
ORDER BY tbl_RESTAURANT.R_PRICE_RANGE;